import Head from 'next/head'
import { SetStateAction, useState } from 'react'
import Countries from  '../components/Countries'

export default function Home({ countries }: any) {
  const [newSearch, setNewSearch] = useState('')


  const searchedCountries = countries.filter((c: { name: string | string[] }) => c?.name?.includes(newSearch))
const handleSearchChange = (event: { target: { value: SetStateAction<string> } }) => {
  setNewSearch(event.target.value)
}


  return (
    <>
      <Head>
        <title>Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-gradient-to-r from-violet-500 to-black">
      <div className="flex h-96 bg-gradient-to-r from-violet-500 to-black">
      <div className="mx-auto"><p className="text-2xl text-center text-white py-10">find countries</p><input className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" onChange={handleSearchChange} /></div>
      </div>
      <div className="flex bg-gradient-to-r from-violet-500 to-black ">
        <div className="mx-auto py-10">
<Countries searchedCountries={searchedCountries} />
</div>
      </div>
      </div>
    </>
  )
}

export const getStaticProps = async() => {
  const res = await fetch('https://restcountries.com/v2/all')

  const countries = await res.json()

  return {
    props: {
      countries
    }
  }
}
